Merged branch "medipacksupport" from "git" into "master"
The following commits were merged:

commit 7e2dc37baa49deb4711c668cdd0fb53c864c0a29
Merge: 021a7ce 87795d9
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Nov 5 10:03:04 2018 +0000

    Merge branch 'medipackSupport' into 'medipacksupport'

    Medipack support

    See merge request adol-c/adol-c!26

commit 87795d9b950519f4d1b81770f2f4518f64ff8a0d
Merge: ab7c2ee b6316ae
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:19:31 2018 +0100

    Merge branch 'medipackSupport' into temp

commit ab7c2eedca9735d0a11b135c024b0d2007e22d7d
Merge: 021a7ce 74108e3
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:14:09 2018 +0100

    Merge remote-tracking branch 'origin/gitlab-master' into temp

commit b6316aefefb5f86bb0b5586445c3014f271bd55c
Merge: cbb56c6 74108e3
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:13:25 2018 +0100

    Merge remote-tracking branch 'origin/gitlab-master' into medipackSupport

commit cbb56c6a0604279b74203715e001f124d4aa38b7
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 23 22:30:28 2018 +0200

    Added suport for ZOS, FOS, FOV forward and reverse.

commit 74108e34106dc9e11ab7534962c3b75efbadf54e
Merge: 1faa0bf 85b1193
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Oct 8 08:53:40 2018 +0000

    Merge branch 'fix_adtl_hov_refcntr' into 'gitlab-master'

    Fix undefined reference to adtl_hov::refcounter::refcnt

    See merge request adol-c/adol-c!24

commit 85b119365a6361d808859579defdd0d0d586253b
Author: Jean-Paul Pelteret <jppelteret@gmail.com>
Date:   Mon Oct 1 20:53:03 2018 +0200

    Fix undefined reference to adtl_hov::refcounter::refcnt

commit 1faa0bff7ddc5336eabb77d17ce97c0fe71d728f
Merge: e1210ea c12d9c6
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Oct 1 12:26:39 2018 +0000

    Merge branch 'docu' into 'gitlab-master'

    Refactor tapeless to traceless

    See merge request adol-c/adol-c!23

commit 434cd6b93137a389a4d6c1fc84748cdace897da3
Merge: 2af3f06 e1210ea
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Fri Sep 28 10:07:41 2018 +0200

    Merge remote-tracking branch 'origin/gitlab-master' into medipackSupport

commit 2af3f06efa924151315122e905e32d952285d027
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Sep 27 14:38:30 2018 +0200

    Missing MeDiPack initialization on trace_on.

commit 4efb33371c5ab4b2ddfab6ed8bbc726ff3ab99cc
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Sep 27 09:55:42 2018 +0200

    Null pointer fix for initialization.

commit c12d9c6cda15631fbec6d3e2eefee4fe2e707d1e
Author: mflehmig <martin.schroschk@tu-dresden.de>
Date:   Thu Sep 20 13:16:06 2018 +0200

    Refactor tapeless to traceless

    As far as I can see, the official wording is traceless forward mode.
    Additonally, the latex label and refs changed to 'traceless'.

commit 021a7ceb14e720ae93d77ee11e1a5053a2a58c8f
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Oct 19 09:25:19 2017 +0200

    Added support for MeDiPack library.

    Enable it with the configure options:
    --enable-medipack --with-medipack=<path to MeDiPack>

    Tutorial on a how to use will follow.

commit 5f191dc963c536e932faa96e4046b17ca9fac34e
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Mon May 7 14:45:13 2018 +0200

    Added support for cbrt function.

commit 86f5528a69197091396a6c709176ad41bfd267bf
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Mar 1 10:31:18 2018 +0100

    Changes for new interface.

commit ca037854dd405c866bc959e1f16187858436d183
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Nov 16 14:31:07 2017 +0100

    Changes to new MeDiPack interface for adjoint values.

commit dcfc71eb0b80b8263a68e94617d394d48d30ee81
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Oct 19 09:25:19 2017 +0200

    Added support for MeDiPack library.

    Enable it with the configure options:
    --enable-medipack --with-medipack=<path to MeDiPack>

    Tutorial on a how to use will follow.